"""ajsute

Revision ID: cfb2936a5a72
Revises: a268404794dd
Create Date: 2025-04-20 20:07:10.994499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb2936a5a72'
down_revision = 'a268404794dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nivel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(length=18), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['discord_id'], ['usuario.discord_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(length=18), nullable=False),
    sa.Column('servidor_id', sa.String(length=18), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['discord_id'], ['usuario.discord_id'], ),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidor.guild_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('servidor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_servidor', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('admin_discord_id', sa.String(length=18), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('guild_id',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'usuario', ['admin_discord_id'], ['discord_id'])
        batch_op.drop_column('nome')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('admin')

    with op.batch_alter_table('servidor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('guild_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=18),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('admin_discord_id')
        batch_op.drop_column('nome_servidor')

    op.drop_table('mensagem')
    op.drop_table('nivel')
    op.drop_table('log')
    # ### end Alembic commands ###
