"""Campo novo na mensagem

Revision ID: e9b7f29aca83
Revises: 02c74f51a91a
Create Date: 2025-04-23 20:21:05.050679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b7f29aca83'
down_revision: Union[str, None] = '02c74f51a91a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canal_id', sa.String(length=21), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagem', schema=None) as batch_op:
        batch_op.drop_column('canal_id')

    # ### end Alembic commands ###
